export const state = {
  sessionToken: null,
  currentUser: null,
  currentPropTab: 'ativas',
  currentAdminTab: 'usuarios',
  todasPropostas: [],
  todosEmitentes: [],
  todasPessoas: [],
  pessoaSelecionadaId: null,
  editandoUsuarioId: null,
  editandoPessoaId: null,
  editandoContatoId: null,
  editandoEmitenteId: null,
  emitentesDoUsuario: [],
  emLogoBase64: null,
  emLogoRemovido: false,
  suspensaoAtual: { id: null, acao: null },
  editandoNumeracaoGrupoId: null,
};
